let tipslist= [];

tipslist.push("When in range, enemies will prioritize attacking the most recently deployed unit.")
tipslist.push("Most sniper units will prioritize attacking aerial enemies.")
tipslist.push("Aerial enemies cannot be blocked and ignore map pathing restrictions, they can only be hit by ranged units or ground units provided with ranged attacks.")
tipslist.push("Make good use of units' traits and talents to enrich your strategies.")
tipslist.push("Units that were knocked out or retreat will be available to use again after their redeployment time is over, but at an increased cost.")
tipslist.push("DEF will directly decrease the amount of physical damage received.")
tipslist.push("Magic damage ignores the target's DEF but is reduced by a percentage of the target's RES.")
tipslist.push("Supporters can reduce the enemy movement speed by 80% every hit. Use this to your advantage to slow the advance of troublesome enemies.")
tipslist.push("Splash Casters can hit all enemies in a radius around the primary target. Use them to deal with large waves of enemies.")
tipslist.push("A unit inflicted with the Cold status effect will have their attack speed reduced by 30%. If they are hit by a Cold effect again during the duration, they will get Frozen and will be unable to act.")
tipslist.push("Retreating a unit refunds half of its deployement cost. Knocked out units do not.")
tipslist.push("BLOCK indicates the number of enemies a unit can block and prevent from advancing forward.")
tipslist.push("Defender units have higher survivability than other units thanks to their innate high HP and DEF.")
tipslist.push("Vanguard units are cheaper to deploy and provide skills to generate deployment points.")
tipslist.push("Medic units cannot attack enemies, however they can heal allies with each attack.")
tipslist.push("Enemies can come equipped with special skills, this will be shown by a yellow bar under them.")
tipslist.push("Silencing an enemy prevents them from unleashing their special skill for the duration of the silence.")
tipslist.push("Deployment points (DP) are required to be able to deploy units. The number of DP available is indicated on the bottom side of the screen and regenerates at a rate of 1 DP per second.")

